apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: calculator-test-pass-sample
  namespace: testkube
spec:
  type: container-executor-pytest/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/techmaharaj/TestKube-PyTest
      branch: main
      path: test-api-endpoint.py
  executionRequest:
    command: ["pytest", "/data/repo/test-api-endpoint.py"]
