apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-pytest-passed-sample
  namespace: testkube
spec:
  type: container-executor-pytest/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/techmaharaj/TestKube-PyTest
      branch: main
      path: weather_service_test.py
  executionRequest:
    command: ["pytest", "/data/repo/weather_service_test.py"]