name: Create Cluster

on:
  push:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Kind Cluster
        uses: helm/kind-action@v1.9.0

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Setup Testkube with Helm
        run: |
          helm repo add kubeshop https://kubeshop.github.io/helm-charts
          helm repo update
          helm install --create-namespace my-testkube kubeshop/testkube

      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1

      - name: Check Pods Status
        run: |
          kubectl get pods -A
          sleep 30
        
      - run: |
          testkube create test --name k6-kubeshop-test --type k6/script --update --test-content-type git-file --git-uri https://github.com/techmaharaj/testkube-GH.git --git-branch main --git-path k6/testkube.js
          testkube run test k6-kubeshop-test -f

      - name: Delete Kind Cluster
        if: always() # Ensure the cluster is deleted even if previous steps fail
        run: |
          kind delete cluster
